#!/usr/bin/bash

current_date=$(date +%Y-%m-%d)
backup_dir="/home/vadim/Backup-$current_date"
backup_report="/home/vadim/backup-report"

if [ ! -d "$backup_dir" ]; then
	mkdir -p "$backup_dir"
	echo "New backup directory created: $backup_dir on $(date)" >>"$backup_report"

	cp /home/vadim/source/* "$backup_dir/"
	echo "Files copied:" >>"$backup_report"
	for file in "$backup_dir"/*; do
		echo "$file" >>"$backup_report"
	done
else
	for file in /home/vadim/source/*; do
		file_name=$(basename "$file")
		backup_file="$backup_dir/$file_name"

		if [ ! -f "$backup_file" ]; then
			cp "$file" "$backup_dir/"
			echo "Copied new file: $file_name" >>"$backup_report"
		else
			if [ "$(stat -c%s "$file")" -ne "$(stat -c%s "$backup_file")" ]; then
				mv "$backup_file" "$backup_file-$current_date"
				cp "$file" "$backup_dir/"
				echo "Updated file: $file_name (renamed old version to $backup_file-$current_date and copied new version)" >>"$backup_report"
			fi
		fi
	done
	echo "Changes made to existing backup directory: $backup_dir on $(date)" >>"$backup_report"
fi
