#!/usr/bin/bash

backup_dir="/home/vadim/"

folders=$(ls -d "$backup_dir"/Backup-* | sort -r)

latest_folder=$(echo "$folders" | head -n 1)

destination_dir="/home/vadim/restore"

find "$latest_folder" -type f ! -name '*-*' -exec cp {} "$destination_dir" \;
