#!/usr/bin/bash

backup_dir="/home/vadim/"

dirs=$(ls -d "$backup_dir"/Backup-* | sort -r)

latest_dir=$(echo "$dirs" | head -n 1)

destination_dir="/home/vadim/restore"

find "$latest_dir" -type f ! -regex '.*[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}.*' -exec cp {} "$destination_dir" \;
