#!/usr/bin/bash

mode="addition"
current_value=1

(tail -f pipi) |
	while true; do
		read -r input
		if [[ $input == "+" ]]; then
			mode="addition"
		elif [[ $input == "*" ]]; then
			mode="multiplication"
		elif [[ $input =~ ^[0-9]+$ ]]; then
			if [[ $mode == "addition" ]]; then
				current_value=$((current_value + input))
			elif [[ $mode == "multiplication" ]]; then
				current_value=$((current_value * input))
			fi
		elif [[ $input == "QUIT" ]]; then
			echo "Stopping."
			pkill -f script5Generator
			break
		else
			echo "Error: incorrect input."
			echo "$input"
			pkill -f script5Generator
			break
		fi
	done
