#!/usr/bin/bash

while true; do
	read -r LINE
	case $LINE in
	"+")
		kill -SIGUSR1 "$(cat .pid)"
		;;
	"*")
		kill -SIGUSR2 "$(cat .pid)"
		;;
	*TERM*)
		kill -SIGTERM "$(cat .pid)"
		exit 0
		;;
	*) ;;
	esac
done
